version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
  # web-tests:
  #   image: vidly_web
  #   volumes:
  #     - ./frontend:/app
  #   command: npm test
